// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aizyujtgptumsuvllamc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpenl1anRncHR1bXN1dmxsYW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjAwNzIsImV4cCI6MjA3MDc5NjA3Mn0.H0C-rH2ODAEBXmst0t8LCbg4XHsPlZxuZ-ZSZt-AVqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});